<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Goldeneye</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>

<body>
    <header class="p-4 bg-blue-500">
        <h1 class="text-center text-xl text-white font-medium">
            New Employee
        </h1>
    </header>
    <div class="p-10">
        <h1 class="text-center font-medium">
               Oops! It seems that what you are trying to search for does not exist.
        </h1>
    </div>
</body>

</html>